### PR TITLE
Update to work with Flask 2.0.0

### PR DESCRIPTION
**Pull request by pgjones**
This should be all that is required to work with Flask 2.0.0. Note
I've pinned to the release candidate at the moment, but this can
change after the release.

@miguelgrinberg This is to help me test that Flask 2.0.0 is doing the right thing, please say if I'm missing anything or not understanding.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Hi @pgjones! I have made the changes for flask 2.x a while ago. They are parked in a branch: https://github.com/miguelgrinberg/aioflask/commit/177dc82b2e2fd6b02c544e7d9d3e9386e07e83a7. I changed a couple more things for consistency, but overall you've made the same change.

**Comment by pgjones** [comment]
Great, I'll close this.

Out of interest what are the `__ident_func__` changes required for? (I'd like to remove these from Werkzeug)

**Comment by miguelgrinberg** [comment]
@pgjones The `__ident_func__` change was necessary to make context locals work inside coroutines. I haven't checked this recently, are Werkzeug's context vars now compatible with coroutines? If they are, then this isn't needed anymore.

**Comment by pgjones** [comment]
Werkzeug's locals are ContextVar backed* in the 2.0.0 release. *Except when they aren't available (Python 3.6) or greenlet doesn't support them (older greenlet versions) see [this logic](https://github.com/pallets/werkzeug/blob/master/src/werkzeug/local.py#L36).

**Comment by miguelgrinberg** [comment]
Sounds good. Then I should be able to remove it in the flask 2 branch. Thanks.

**Pull request closed without merging**
